# Generated by Django 5.0.1 on 2025-12-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0002_alter_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assigned_images',
            field=models.ManyToManyField(blank=True, help_text='Specific subset of images assigned to this clinician. If empty, implies all images.', related_name='assignments_subset', to='evaluator.image'),
        ),
    ]
